# Site settings
title: "BacklogJS &middot; JavaScript talks made right"
description: "BacklogJS &middot; JavaScript talks made right"
keywords: "BacklogJS, backlog, js, javascript, hangouts, backlogjs, talks"
baseurl: ""
url: "http://backlog.js.org"
